lib/Form/Transformer/PathToDocumentTransformer.php
<?php

namespace Symfony\Cmf\Bundle\AdminBundle\Form\Transformer;

use Symfony\Component\Form\DataTransformerInterface;
use Doctrine\ODM\PHPCR\DocumentManagerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class PathToDocumentTransformer implements DataTransformerInterface
{
    private $manager;

    public function __construct(DocumentManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    /**
     * Transforms an object (issue) to a string (number).
     *
     * @param  Issue|null $issue
     * @return string
     */
    public function transform($document)
    {
        if (null === $document) {
            return '';
        }

        return $this->manager->getNodeForDocument($document)->getPath();
    }

    /**
     * Transforms a string (number) to an object (issue).
     *
     * @param  string $issueNumber
     * @return Issue|null
     * @throws TransformationFailedException if object (issue) is not found.
     */
    public function reverseTransform($path)
    {
        $document = $this->manager->find(null, $path);

        if (null === $document) {
            throw new TransformationFailedException(sprintf(
                'Could not find document for path "%s"',
                $path
            ));
        }

        return $document;
    }
}

lib/Form/Type/PhpcrOdmParentPathType.php
<?php

namespace Symfony\Cmf\Bundle\AdminBundle\Form\Type;

use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\ODM\PHPCR\DocumentManagerInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Cmf\Bundle\AdminBundle\Form\Transformer\PathToDocumentTransformer;

class PhpcrOdmParentPathType extends AbstractType
{
    private $manager;

    public function __construct(DocumentManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer(new PathToDocumentTransformer($this->manager));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
    }

    public function getParent()
    {
        return TextType::class;
    }

    public function getName()
    {
        return 'phpcrodm_parent_path';
    }
}

lib/Controller/ResourceController.php
<?php

namespace Symfony\Cmf\Bundle\AdminBundle\Controller;

use Symfony\Component\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;

class ResourceController
{
    private $templating;

    public function __construct(EngineInterface $templating)
    {
        $this->templating = $templating;
    }

    public function dashboardAction(Request $request)
    {
        return $this->templating->renderResponse('CmfAdminBundle:Resource:dashboard.html.twig');
    }
}

lib/Resources/views/Crud/Breadcrumb/_create.html.twig
{% import 'CmfAdminBundle:Crud/Macro:breadcrumb.html.twig' as breadcrumb %}

{% set breadcrumbs = [
        { label: (metadata.applicationName~'.ui.'~metadata.pluralName)|trans, url: path(configuration.getRouteName('index'), configuration.vars.route.parameters|default({})) },
        { label: 'sylius.ui.new'|trans }
    ]
%}

{{ breadcrumb.crumble(breadcrumbs) }}

lib/Resources/views/Crud/Breadcrumb/_index.html.twig
{% import 'CmfAdminBundle:Crud/Macro:breadcrumb.html.twig' as breadcrumb %}

{% set breadcrumbs = [
        { label: (metadata.applicationName~'.ui.'~metadata.pluralName)|trans },
    ]
%}

{{ breadcrumb.crumble(breadcrumbs) }}

lib/Resources/views/Crud/Breadcrumb/_update.html.twig
{% import 'CmfAdminBundle:Crud/Macro:breadcrumb.html.twig' as breadcrumb %}

{% set breadcrumbs = [
        { label: (metadata.applicationName~'.ui.'~metadata.pluralName)|trans, url: path(configuration.getRouteName('index'), configuration.vars.route.parameters|default({})) },
        { label: resource.code|default(resource.id)},
        { label: 'sylius.ui.edit'|trans }
    ]
%}

{{ breadcrumb.crumble(breadcrumbs) }}

lib/Resources/views/Crud/Macro/breadcrumb.html.twig
{% macro crumble(crumbs = {}) %}
<div class="ui breadcrumb">
    {% for crumb in crumbs %}
        {% if loop.last %}
            <div class="active section">{{ crumb.label }}</div>
        {% elseif crumb.url is defined %}
            <a href="{{ crumb.url }}" class="section">{{ crumb.label }}</a>
            <i class="right chevron icon divider"></i>
        {% else %}
            <div class="section">{{ crumb.label }}</div>
            <i class="right chevron icon divider"></i>
        {% endif %}
    {% else %}
        <a href="{{ path('sylius_admin_dashboard') }}" class="section">{{ 'sylius.ui.administration'|trans }}</a>
    {% endfor %}
</div>
{% endmacro %}

lib/Resources/views/Crud/_grid.html.twig
{% import 'SyliusUiBundle:Macro:pagination.html.twig' as pagination %}
{% import 'SyliusUiBundle:Macro:buttons.html.twig' as buttons %}
{% import 'SyliusUiBundle:Macro:messages.html.twig' as messages %}

{% set definition = grid.definition %}
{% set data = grid.data %}

{% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) %}

{% if definition.filters|length > 0 %}
    <div class="ui segment">
        <form method="get" action="{{ path }}" class="ui form">
            <div class="two fields">
            {% for filter in definition.filters %}
                {{ sylius_grid_render_filter(grid, filter) }}

                {% if loop.index0 % 2 %}
                    </div>
                    <div class="two fields">
                {% endif %}
            {% endfor %}
            </div>
            {{ buttons.filter() }}
            {{ buttons.resetFilters(path) }}
        </form>
    </div>
{% endif %}

<div class="ui segment">
    {{ pagination.render(data) }}
    {% if data|length > 0 %}
        <table class="ui sortable stackable celled table">
            <thead>
            <tr>
                {% for field in definition.fields %}
                    <th{% if grid.isSortedBy(field.name) %} class="sorted {{ 'asc' == grid.getSortingOrder(field.name) ? 'ascending' : 'descending' }}"{% endif %}>
                        {{ field.label|trans }}
                    </th>
                {% endfor %}
                {% if definition.actionGroups.item is defined and definition.getActions('item')|length > 0 %}
                    <th>{{ 'sylius.ui.actions'|trans }}</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for row in data %}
                <tr>
                    {% for field in definition.fields %}
                        <td>{{ sylius_grid_render_field(grid, field, row) }}</td>
                    {% endfor %}
                    {% if definition.actionGroups.item is defined and definition.getActions('item')|length > 0 %}
                        <td>
                            <div class="ui buttons">
                                {% for action in definition.getActions('item') %}
                                    {{ sylius_grid_render_action(grid, action, row) }}
                                {% endfor %}
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        {{ messages.info('sylius.ui.no_results_to_display'|trans) }}
    {% endif %}
    {{ pagination.render(data) }}
</div>

lib/Resources/views/Crud/create.html.twig
{% extends cmf_admin_layout_template %}

{% import 'SyliusUiBundle:Macro:headers.html.twig' as headers %}

{% set header = configuration.vars.header|default(metadata.applicationName~'.ui.new_'~metadata.name) %}

{% block title %}{{ parent() }} {{ header|trans }}{% endblock %}

{% form_theme form 'CmfAdminBundle:Form:theme.html.twig' %}

{% block content %}
{{ headers.default(header|trans, configuration.vars.icon|default('plus'), configuration.vars.subheader|default(null)|trans) }}

{% include configuration.vars.templates.breadcrumb|default('CmfAdminBundle:Crud/Breadcrumb:_create.html.twig') %}

{{ form_start(form, {'action': path(configuration.vars.route.name|default(configuration.getRouteName('create')), configuration.vars.route.parameters|default({})), 'attr': {'class': 'ui form', 'novalidate': 'novalidate'}}) }}
    <div class="ui segment">
        {% if configuration.vars.templates.form is defined %}
            {% include configuration.vars.templates.form %}
        {% else %}
            {{ form_widget(form) }}
        {% endif %}
        {% include 'SyliusUiBundle:Form:_create.html.twig' with {'cancel_path': path(configuration.getRouteName('index'), configuration.vars.route.parameters|default({}))} %}
    </div>
{{ form_row(form._token) }}
{{ form_end(form, {'render_rest': false}) }}
{% endblock %}

lib/Resources/views/Crud/index.html.twig
{% extends cmf_admin_layout_template %}

{% import 'SyliusUiBundle:Macro:headers.html.twig' as headers %}

{% set definition = resources.definition %}
{% set data = resources.data %}

{% set header = configuration.vars.header|default(metadata.applicationName~'.ui.'~metadata.pluralName) %}

{% block title %}{{ parent() }} {{ header|trans }}{% endblock %}

{% block content %}
<div class="ui stackable two column grid">
    <div class="column">
        {{ headers.default(header|trans, configuration.vars.icon|default('list'), configuration.vars.subheader|default(null)|trans) }}

        {% include configuration.vars.templates.breadcrumb|default('CmfAdminBundle:Crud/Breadcrumb:_index.html.twig') %}
    </div>
    <div class="middle aligned column">
        <div class="ui right floated buttons">
            {% if definition.actionGroups.main is defined and definition.getActions('main')|length > 0 %}
                {% for action in definition.getActions('main') %}
                    {{ sylius_grid_render_action(resources, action, null) }}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{{ sylius_grid_render(resources, 'CmfAdminBundle:Crud:_grid.html.twig') }}

{% endblock %}

lib/Resources/views/Crud/update.html.twig
{% extends cmf_admin_layout_template %}

{% import 'SyliusUiBundle:Macro:headers.html.twig' as headers %}
{% import 'SyliusUiBundle:Macro:buttons.html.twig' as buttons %}

{% set header = configuration.vars.header|default(metadata.applicationName~'.ui.edit_'~metadata.name) %}

{% block title %}{{ parent() }} {{ header|trans }}{% endblock %}

{% form_theme form 'CmfAdminBundle:Form:theme.html.twig' %}

{% block content %}
{{ headers.default(header|trans, configuration.vars.icon|default('pencil'), configuration.vars.subheader|default(null)|trans) }}

{% include configuration.vars.templates.breadcrumb|default('CmfAdminBundle:Crud/Breadcrumb:_update.html.twig') %}

{{ form_start(form, {'action': path(configuration.getRouteName('update'), configuration.vars.route.parameters|default({ 'id': resource.id })), 'attr': {'class': 'ui form', 'novalidate': 'novalidate'}}) }}
    <div class="ui segment">
        <input type="hidden" name="_method" value="PUT" />
        {% if configuration.vars.templates.form is defined %}
            {% include configuration.vars.templates.form %}
        {% else %}
            {{ form_widget(form) }}
        {% endif %}
        {% include 'SyliusUiBundle:Form:_saveChanges.html.twig' with {'cancel_path': path(configuration.getRouteName('index'), configuration.vars.route.parameters|default({}))} %}
    </div>
{{ form_row(form._token) }}
{{ form_end(form, {'render_rest': false}) }}
{% endblock %}

lib/Resources/views/Form/theme.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block form_row -%}
    <div class="{% if required %}required {% endif %}field{% if (not compound or force_error|default(false)) and not valid %} error{% endif %}">
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{%- endblock form_row %}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
        {%- for error in errors -%}
            <div class="ui red pointing label">
            {{ error.message }}
            </div>
        {%- endfor -%}
    {%- endif -%}
{%- endblock form_errors -%}

{% block checkbox_row -%}
    <div class="field{% if (not compound or force_error|default(false)) and not valid %} error{% endif %}">
        <div class="ui toggle checkbox">
            <label>{{ label }}</label>
            {{- form_widget(form) -}}
            {{- form_errors(form) -}}
        </div>
    </div>
{%- endblock checkbox_row %}

{% block choice_row -%}
    <div class="{% if required %}required {% endif %}field{% if (not compound or force_error|default(false)) and not valid %} error{% endif %}">
        {{- form_label(form) -}}
        {% set attr = attr|merge({'class': attr.class|default ~ ' ui dropdown'}) %}
        {{- form_widget(form, {'attr': attr}) -}}
        {{- form_errors(form) -}}
    </div>
{%- endblock choice_row %}

{%- block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
        <div class="grouped fields">
            {%- for child in form %}
                <div class="field">
                    <div class="ui toggle checkbox">
                        {{- form_label(child, null, {translation_domain: choice_translation_domain}) -}}
                        {{- form_widget(child) -}}
                    </div>
                </div>
            {% endfor -%}
        </div>
    </div>
{%- endblock choice_widget_expanded -%}

{% block percent_widget -%}
    <div class="ui right labeled input">
        {{- form_widget(form) -}}
        <div class="ui basic label">%</div>
    </div>
{%- endblock percent_widget %}

{% block collection_widget -%}
    {% from 'SyliusResourceBundle:Macros:notification.html.twig' import error %}
    {% set attr = attr|merge({'class': attr.class|default ~ ' controls collection-widget'}) %}

    {% spaceless %}
        <div data-form-type="collection" {{ block('widget_container_attributes') }}
            {% if prototype is defined and allow_add %}
                data-prototype='{{ _self.collection_item(prototype, allow_delete, button_delete_label, '__name__')|e }}'
            {%- endif -%}
        >
            {{ error(form.vars.errors) }}

            {% if prototypes|default is iterable %}
                {% for key, subPrototype in prototypes %}
                    <input type="hidden" data-form-prototype="{{ key }}" value="{{ _self.collection_item(subPrototype, allow_delete, button_delete_label, '__name__')|e }}" />
                {% endfor %}
            {% endif %}

            <div data-form-collection="list">
                {% for child in form %}
                    {{ _self.collection_item(child, allow_delete, button_delete_label, loop.index0) }}
                {% endfor %}
            </div>

            {% if prototype is defined and allow_add %}
                <a href="#" class="ui labeled icon button" data-form-collection="add">
                    <i class="plus square outline icon"></i>
                    {{ button_add_label|trans }}
                </a>
            {% endif %}
        </div>
    {% endspaceless %}
{%- endblock collection_widget %}

{% macro collection_item(form, allow_delete, button_delete_label, index) %}
    {% spaceless %}
        <div data-form-collection="item" data-form-collection-index="{{ index }}">
            {{ form_widget(form) }}
            {% if allow_delete %}
                <a href="#" data-form-collection="delete" class="ui red labeled icon button" style="margin-bottom: 1em;">
                    <i class="trash icon"></i>
                    {{ button_delete_label|trans }}
                </a>
            {% endif %}
        </div>
    {% endspaceless %}
{% endmacro %}

{% block sylius_translations_row -%}
    <h4 class="ui dividing header">{{ form_label(form) }}</h4>
    <div class="ui grid">
        {% for translation in form %}
            <div class="four wide column">
                {{ form_label(translation, translation.vars.name) }}
            </div>
            <div class="twelve wide column">
                {{ form_widget(translation) }}
            </div>
            {{- form_errors(form) -}}
        {% endfor %}
    </div>
{%- endblock sylius_translations_row %}

lib/Resources/views/Grid/Field/enabled.html.twig
{% import '@SyliusUi/Macro/labels.html.twig' as label %}
{{ label.status(data) }}

lib/Resources/views/Grid/Field/humanized.html.twig
{{ data|humanize }}

lib/Resources/views/Grid/Field/label.html.twig
{% import '@SyliusUi/Macro/labels.html.twig' as label %}
{{ label.default(data) }}

lib/Resources/views/Grid/Field/nameAndDescription.html.twig
<strong>{{ data.name }}</strong>
{% if data.description is not empty %}
    <p>{{ data.description }}</p>
{% endif %}

lib/Resources/views/Grid/Field/yesNo.html.twig
{% import '@SyliusUi/Macro/labels.html.twig' as label %}
{{ label.yesNo(data) }}

lib/Resources/views/Grid/Filter/boolean.html.twig
{% form_theme form 'CmfAdminBundle:Form:theme.html.twig' %}
{{ form_row(form) }}

lib/Resources/views/Grid/Filter/string.html.twig
{% form_theme form 'CmfAdminBundle:Form:theme.html.twig' %}
{{ form_row(form.type, {'label': filter.label|trans}) }}
{{ form_row(form.value) }}

lib/Resources/views/Link/_create.html.twig
{% import 'SyliusUiBundle:Macro:buttons.html.twig' as buttons %}
{{ buttons.create(path(grid.requestConfiguration.getRouteName('create'))) }}

lib/Resources/views/Link/_delete.html.twig
{% import 'SyliusUiBundle:Macro:buttons.html.twig' as buttons %}

{{ buttons.delete(path(grid.requestConfiguration.getRouteName('delete'), {'id': data.id})) }}

lib/Resources/views/Link/_update.html.twig
{% import 'SyliusUiBundle:Macro:buttons.html.twig' as buttons %}

{{ buttons.edit(path(grid.requestConfiguration.getRouteName('update'), {'id': data.id})) }}

lib/Resources/views/Macroasd/buttons.html.twig
{% macro default(url, message, id, icon, class) %}
<a class="btn{% if class is not empty %} {{ class }} {% else %} btn-default{% endif %}" {% if id is not empty %} id="{{ id }}"{% endif %} href="{{ url }}">
        {% if icon is not empty %}
            <span class="glyphicon glyphicon-{{ icon }}"></span>
        {% endif %}
        {{ message|trans }}
    </a>
{% endmacro %}

{% macro show(url, message, id, class) %}
    {% import _self as buttons %}

    {% if message is empty %}
        {% set message = 'cmf.admin.show'|trans %}
    {% endif %}

    {{ buttons.default(url, message, id, 'search') }}
{% endmacro %}

{% macro create(url, message, id) %}
    {% import _self as buttons %}

    {% if message is empty %}
        {% set message = 'cmf.admin.create'|trans %}
    {% endif %}

    {{ buttons.default(url, message, id, 'plus', 'btn-primary') }}
{% endmacro %}

{% macro edit(url, message, id) %}
    {% import _self as buttons %}

    {% if message is empty %}
        {% set message = 'cmf.admin.edit'|trans %}
    {% endif %}

    {{ buttons.default(url, message, id, 'pencil') }}
{% endmacro %}

{% macro filter(message) %}
    <button class="ui blue labeled icon button" type="submit">
        <i class="icon search"></i> {{ message is empty ? 'cmf.admin.filter'|trans : message }}
    </button>
{% endmacro %}

{% macro resetFilters(url, message) %}
    <a class="ui labeled icon button" href="{{ url }}">
        <i class="icon remove"></i> {{ message is empty ? 'cmf.admin.clear_filters'|trans : message }}
    </a>
{% endmacro %}

{% macro delete(url, message) %}
    <form action="{{ url }}" method="post">
        <input type="hidden" name="_method" value="DELETE">
        <button class="btn btn-danger" type="submit" data-requires-confirmation>
            <i class="glyphicon glyphicon-remove"></i> {{ message is empty ? 'cmf.admin.delete'|trans : message }}
        </button>
    </form>
{% endmacro %}

lib/Resources/views/Macroasd/common.html.twig
{% macro attributes(attributes) %}
    {% for name, value in attributes %}
        {%- if value is not none and value is not same as(false) -%}
            {{- ' %s="%s"'|format(name, value is same as(true) ? name|e : value|e)|raw -}}
        {%- endif -%}
    {%- endfor -%}
{% endmacro %}

lib/Resources/views/Macroasd/headers.html.twig
{% macro default(header, icon, subheader) %}
<h1 class="ui header">
    {% if icon is not empty %}
    <i class="circular {{ icon }} icon"></i>
    {% endif %}
    <div class="content">
        {{ header }}
        {% if subheader is not empty %}
        <div class="sub header">{{ subheader }}</div>
        {% endif %}
    </div>
</h1>
{% endmacro %}

lib/Resources/views/Macroasd/labels.html.twig
{% macro status(status) %}
    {% import _self as labels %}

    {% if status %}
        {{ labels.enabled() }}
    {% else %}
        {{ labels.disabled() }}
    {% endif %}
{% endmacro %}

{% macro enabled() %}
    <span class="ui teal label">
        <i class="checkmark icon"></i>
        {{ 'sylius.ui.enabled'|trans }}
    </span>
{% endmacro %}

{% macro disabled() %}
    <span class="ui red label">
        <i class="remove icon"></i>
        {{ 'sylius.ui.disabled'|trans }}
    </span>
{% endmacro %}

lib/Resources/views/Macroasd/messages.html.twig
{% macro default(message, icon, type) %}
    <div class="ui icon {{ type|default('') }} message">
        <i class="{{ icon }} icon"></i>
        <div class="content">
            {% if type is not empty %}
            <div class="header">
                {% set header = 'sylius.ui.'~type %}
                {{ header|trans }}
            </div>
            {% endif %}
            <p>{{ message }}</p>
        </div>
    </div>
{% endmacro %}

{% macro info(message) %}
    {% import _self as messages %}
    {{ messages.default(message, 'info circle', 'info') }}
{% endmacro %}

{% macro success(message) %}
    {% import _self as messages %}
    {{ messages.default(message, 'checkmark', 'success') }}
{% endmacro %}

{% macro error(message) %}
    {% import _self as messages %}
    {{ messages.default(message, 'remove', 'error') }}
{% endmacro %}

lib/Resources/views/Macroasd/pagination.html.twig
{% macro render(paginator)  %}
    {% if paginator.haveToPaginate() %}
    <div class="ui pagination menu">
        {% for page_number in 1..paginator.nbPages %}
        <a class="{% if page_number == paginator.currentPage %}active {% endif %}item" href="{{ path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge(app.request.query.all)|merge({'page': page_number})) }}">{{ page_number }}</a>
        {% endfor %}
    </div>
    {% endif %}
{% endmacro %}

lib/Resources/views/Menuasd/knp_menu.html.twig
{% extends 'knp_menu.html.twig' %}

{% block item %}
{% import "knp_menu.html.twig" as macros %}
{% if item.displayed %}
    {%- set attributes = item.attributes %}
    {%- set is_dropdown = attributes.dropdown|default(false) %}
    {%- set divider_prepend = attributes.divider_prepend|default(false) %}
    {%- set divider_append = attributes.divider_append|default(false) %}

{# unset bootstrap specific attributes #}
    {%- set attributes = attributes|merge({'dropdown': null, 'divider_prepend': null, 'divider_append': null }) %}

    {%- if divider_prepend %}
        {{ block('dividerElement') }}
    {%- endif %}

{# building the class of the item #}
    {%- set classes = item.attribute('class') is not empty ? [item.attribute('class')] : [] %}
    {%- if matcher.isCurrent(item) %}
        {%- set classes = classes|merge([options.currentClass]) %}
    {%- elseif matcher.isAncestor(item, options.depth) %}
        {%- set classes = classes|merge([options.ancestorClass]) %}
    {%- endif %}
    {%- if item.actsLikeFirst %}
        {%- set classes = classes|merge([options.firstClass]) %}
    {%- endif %}
    {%- if item.actsLikeLast %}
        {%- set classes = classes|merge([options.lastClass]) %}
    {%- endif %}

{# building the class of the children #}
    {%- set childrenClasses = item.childrenAttribute('class') is not empty ? [item.childrenAttribute('class')] : [] %}
    {%- set childrenClasses = childrenClasses|merge(['menu_level_' ~ item.level]) %}

{# adding classes for dropdown #}
    {%- if is_dropdown %}
        {%- set classes = classes|merge(['dropdown']) %}
        {%- set childrenClasses = childrenClasses|merge(['dropdown-menu']) %}
    {%- endif %}

{# putting classes together #}
    {%- if classes is not empty %}
        {%- set attributes = attributes|merge({'class': classes|join(' ')}) %}
    {%- endif %}
    {%- set listAttributes = item.childrenAttributes|merge({'class': childrenClasses|join(' ') }) %}

{# displaying the item #}
    <li{{ macros.attributes(attributes) }}>
        {%- if is_dropdown %}
            {{ block('dropdownElement') }}
        {%- elseif item.uri is not empty and (not item.current or options.currentAsLink) %}
            {{ block('linkElement') }}
        {%- else %}
            {{ block('spanElement') }}
        {%- endif %}
{# render the list of children#}
        {{ block('list') }}
    </li>

    {%- if divider_append %}
        {{ block('dividerElement') }}
    {%- endif %}
{% endif %}
{% endblock %}

{% block dividerElement %}
{% if item.level == 1 %}
    <li class="divider-vertical"></li>
{% else %}
    <li class="divider"></li>
{% endif %}
{% endblock %}

{% block linkElement %}
	<a href="{{ item.uri }}"{{ macros.attributes(item.linkAttributes) }}>
		{% if item.attribute('icon') is not empty  %}
    		<i class="{{ item.attribute('icon') }}"></i> 
    	{% endif %}
		{{ block('label') }}
	</a>
{% endblock %}

{% block spanElement %}
	<span>{{ macros.attributes(item.labelAttributes) }}>
		{% if item.attribute('icon') is not empty  %}
    		<i class="{{ item.attribute('icon') }}"></i> 
    	{% endif %}
		{{ block('label') }}
	</span>
{% endblock %}

{% block dropdownElement %}
    {%- set classes = item.linkAttribute('class') is not empty ? [item.linkAttribute('class')] : [] %}
    {%- set classes = classes|merge(['dropdown-toggle']) %}
    {%- set attributes = item.linkAttributes %}
    {%- set attributes = attributes|merge({'class': classes|join(' ')}) %}
    {%- set attributes = attributes|merge({'data-toggle': 'dropdown'}) %}
    <a href="#"{{ macros.attributes(attributes) }}>
    	{% if item.attribute('icon') is not empty  %}
    		<i class="{{ item.attribute('icon') }}"></i> 
    	{% endif %}
    	{{ block('label') }} 
    	<b class="caret"></b>
    </a>
{% endblock %}

{% block label %}{{ item.label|trans }}{% endblock %}

lib/Resources/views/Resourceasd/dashboard.html.twig
{% extends cmf_admin_layout_template %}